import { Metadata } from "next";
import localFont from "next/font/local"; 
import Navbar from "@/components/navbar";
import Footer from "@/components/footer"
import "./globals.css";  

const titilliumWeb = localFont({
  src: [
    {
      path: './fonts/TitilliumWeb-Regular.woff',  
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/TitilliumWeb-Bold.woff',  
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-titillium-web',  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${titilliumWeb.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
